_target_: src.models.segmentation.Segmentation
training: True
pruning: False
#
#sch:
#  n_steps:
#    - 120000
#    - 160000
#  max_iter: 180000
#  WARMUP_FACTOR: 0.3333
#  WARMUP_ITERS: 500
#  WARMUP_METHOD: "linear"
#  GAMMA: 0.1
#
#defaults:
#  - optim: sgd.yaml
#
#optim:
#  sgd:
#    lr: 0.01
#    momentum: 0.9
#    weight_decay: 0.0001
